# Generated by Django 4.0 on 2021-12-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('job_title', models.CharField(max_length=255, verbose_name='title')),
                ('functions', models.CharField(max_length=255, verbose_name='functions')),
                ('detailed_functions', models.CharField(max_length=255, verbose_name='detailed function')),
                ('seniority', models.CharField(max_length=255, verbose_name='seniority')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('postal_code', models.IntegerField(verbose_name='postal code')),
                ('linekdin', models.URLField(verbose_name='linkedin url')),
                ('organization', models.CharField(max_length=255, verbose_name='organization name')),
                ('domain', models.CharField(max_length=255, verbose_name='organization domain')),
                ('organization_phone', models.IntegerField(verbose_name='organization phone')),
                ('organization_facebook', models.URLField(verbose_name='organization facebook url')),
                ('organization_linkedin', models.URLField(verbose_name='organization linkedin numerical urls')),
                ('organization_twitter', models.URLField(verbose_name='organization twitter url')),
                ('organization_website', models.URLField(verbose_name='organization website url')),
                ('organization_angellist', models.URLField(verbose_name='organization angellist url')),
                ('organization_founded', models.IntegerField(verbose_name='organization_founded_year')),
                ('hq_city', models.CharField(max_length=255, verbose_name='organization_hq_location_city')),
                ('hq_postal_code', models.IntegerField(verbose_name='organization_hq_location_postal_code')),
                ('hq_state', models.CharField(max_length=255, verbose_name='organization_hq_location_state')),
                ('hq_country', models.CharField(max_length=255, verbose_name='organization_hq_location_country')),
                ('num_current_employees', models.IntegerField(verbose_name='organization_num_current_employees')),
                ('languages', models.CharField(max_length=255, verbose_name='organization_languages')),
                ('industries', models.CharField(max_length=255, verbose_name='organization_industries')),
            ],
        ),
    ]
